name: CI

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    build:
        name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}

        strategy:
            matrix:
                node: ['16.x']
                os: [ubuntu-20.04]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - run: yarn install

            - run: yarn run build 

 